In [1]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv('drive/MyDrive/Exercise-CarData.csv')

In [ ]:
print(data)
print(data.describe())

In [16]:
# All rows, all columns except last 
X = data.iloc[:,:-1].values
print(X)
print('\n')
# Only last column  
Y = data.iloc[: , -1].values
print(Y)

[[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


[1165 1165 1165 ... 1015 1015 1114]


In [18]:
# 4a. Removing the row with all null values

# data.dropna(axis=0,how='all',inplace=True)
# print('New Dataset : \n',data)

data.dropna(axis=0,how='any',inplace=True)
print('New Dataset : \n',data)

New Dataset : 
       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
5              5  12950  32.0  61000  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1425        1425   7950  80.0     ??  ...         0  1300      4    1000
1429        1429   8950  78.0  24000  ...         1  1300      5    1065
1430        1430   8450  80.0  23000  ...         0  1300      3    1015
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1111 rows x 11 columns]


In [21]:
data = pd.read_csv('drive/MyDrive/Exercise-CarData.csv')

updated_df = data;
updated_df['Age']=updated_df['Age'].fillna(updated_df['Age'].mean())
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1436 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [26]:
updated_df = data;
updated_df['FuelType']=updated_df['FuelType'].fillna("No Type")
updated_df.info()

updated_df = data;
updated_df['MetColor']=updated_df['MetColor'].fillna("No Color")
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1436 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1436 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1436 non

In [27]:
#Using SimpleImputer from Scikit-Learn Library 

In [29]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 

In [30]:
data = pd.read_csv('drive/MyDrive/Exercise-CarData.csv')

In [31]:
# All rows, all columns except last 
X = data.iloc[:, :-1].values 
  
# Only last column  
Y = data.iloc[:, -1].values 

print("\n\nInput : \n", X) 
print("\n\nOutput: \n", Y) 



Input : 
 [[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


Output: 
 [1165 1165 1165 ... 1015 1015 1114]


In [32]:
# All rows, all columns except last 
X = data.iloc[:,:-1].values
print(X)
print('\n')
# Only last column  
Y = data.iloc[: , -1].values
print(Y)

[[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


[1165 1165 1165 ... 1015 1015 1114]


In [40]:
update_data =data;
update_data['Age'] = update_data['Age'].fillna(update_data['Age'].mean())
print(update_data)

      Unnamed: 0  Price        Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.000000  46986  ...         0  2000  three    1165
1              1  13750  23.000000  72937  ...         0  2000      3    1165
2              2  13950  24.000000  41711  ...         0  2000      3    1165
3              3  14950  26.000000  48000  ...         0  2000      3    1165
4              4  13750  30.000000  38500  ...         0  2000      3    1170
...          ...    ...        ...    ...  ...       ...   ...    ...     ...
1431        1431   7500  55.672156  20544  ...         0  1300      3    1025
1432        1432  10845  72.000000     ??  ...         0  1300      3    1015
1433        1433   8500  55.672156  17016  ...         0  1300      3    1015
1434        1434   7250  70.000000     ??  ...         0  1300      3    1015
1435        1435   6950  76.000000      1  ...         0  1600      5    1114

[1436 rows x 11 columns]


In [43]:
imputer = SimpleImputer(missing_values = np.nan,strategy = "mean")
imputer = imputer.fit(X[:, 1:3]) 
X[:, 1:3] = imputer.transform(X[:, 1:3])
print("\n\nNew Input with Mean Value for NaN : \n\n", X) 



New Input with Mean Value for NaN : 

 [[0 13500.0 23.0 ... 0 2000 'three']
 [1 13750.0 23.0 ... 0 2000 '3']
 [2 13950.0 24.0 ... 0 2000 '3']
 ...
 [1433 8500.0 55.67215568862275 ... 0 1300 '3']
 [1434 7250.0 70.0 ... 0 1300 '3']
 [1435 6950.0 76.0 ... 0 1600 '5']]
